### ISSUE TITLE
Dependency Container fails to work inside Panel

### ISSUE THREAD

**Issue by Artexis10** [epartment/nova-dependency-container#156]
Having an issue using NovaDependencyContainer inside of a panel, although the same code is functional outside of it. Any thoughts on how to fix the problem?

**Comment by ragingdave** [comment]
Would you be able to explain the "issue" you are experiencing actually is?

**Comment by Artexis10** [comment]
Issue is that when NovaDependencyContainer is inside a Panel, it fails to react to a field's state changing:

```
new Panel('Header', [
                Boolean::make('Use custom header', 'is_active_2')
                    ->help('If unchecked, the default header will be used'),

                NovaDependencyContainer::make([
                    Select::make('Menu')->options($menus),

                    Flexible::make('Buttons')->button('Add Button')->stacked()->limit(5)
                        ->addLayout('Round Button', 'round_button', [
                            Text::make('Label', 'label'),
                            Text::make('Link', 'link'),
                        ])
                        ->addLayout('Transparent Button', 'transparent_button', [
                            Text::make('Label', 'label'),
                            Text::make('Link', 'link'),
                        ])
                ])->dependsOn('is_active_2', 1),
            ]),
```

When I don't nest the NovaDependencyContainer, it works as intended:

```
Boolean::make('Use custom header', 'is_active')
                ->help('If unchecked, the default header will be used'),

            NovaDependencyContainer::make([
                Select::make('Menu')->options($menus),

                Flexible::make('Buttons')->button('Add Button')->stacked()->limit(5)
                    ->addLayout('Round Button', 'round_button', [
                        Text::make('Label', 'label'),
                        Text::make('Link', 'link'),
                    ])
                    ->addLayout('Transparent Button', 'transparent_button', [
                        Text::make('Label', 'label'),
                        Text::make('Link', 'link'),
                    ])
            ])->dependsOn('is_active', 1),
```

Some pictures to show:

![Screenshot 2021-03-01 173807](https://user-images.githubusercontent.com/54939745/109521357-e4217800-7ab5-11eb-9519-5c2fc0c2342b.png)

![Screenshot 2021-03-01 173837](https://user-images.githubusercontent.com/54939745/109521366-e7b4ff00-7ab5-11eb-84bd-7543e5c44e55.png)

![Screenshot 2021-03-01 173850](https://user-images.githubusercontent.com/54939745/109521370-e97ec280-7ab5-11eb-8a2b-d91da2890561.png)

**Comment by wize-wiz** [comment]
@Artexis10 Are you using the master or the development branch? Which version of Nova are you using?

**Comment by Artexis10** [comment]
I'm using the master branch, version 1.2, and Nova 3.0.

**Comment by Tarpsvo** [comment]
This was an issue with Nova Page Manager, not panels or dependency container.

Fixed in page manager version 3.3.0. The issue can be closed.

**Comment by Artexis10** [comment]
Issue is still present, even with Nova Page Manager version 3.3.0.

**Comment by ragingdave** [comment]
After testing this it appears to be working as expected.

Example code confirmed working:
```
            new Panel('Header', [
                \Laravel\Nova\Fields\Boolean::make('Use custom header', 'is_active_2')
                    ->help('If unchecked, the default header will be used'),

                NovaDependencyContainer::make([
                    Select::make('Menu')->options([]),

                    \Whitecube\NovaFlexibleContent\Flexible::make('Buttons')->button('Add Button')->stacked()->limit(5)
                        ->addLayout('Round Button', 'round_button', [
                            Text::make('Label', 'label'),
                            Text::make('Link', 'link'),
                        ])
                            ->addLayout('Transparent Button', 'transparent_button', [
                                Text::make('Label', 'label'),
                                Text::make('Link', 'link'),
                            ])
                ])->dependsOn('is_active_2', 1),
            ]),
```

When I toggle the boolean field, the fields in the container are properly hidden/shown accordingly.

Using:
```
            "name": "whitecube/nova-flexible-content",
            "version": "v0.2.8",

# And 

            "name": "laravel/nova",
            "version": "3.27.0",
```
